batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 65
model_path: Models/04_sentence_recognition\202510262029
train_epochs: 5
train_workers: 20
vocab: ' "#''(),-.01234589:ABCDEFGHIJKLMNOPRSTUVWYabcdefghijklmnopqrstuvwxy'
width: 1408
